export enum VehicleType {
  autoTransporter = 'autoTransporter',
  onboard = 'onboard',
  jumbo = 'jumbo',
  closed = 'closed',
  isotherm = 'isotherm',
  isothermRefrigerated = 'isothermRefrigerated',
  containerTransporter = 'containerTransporter',
  mega = 'mega',
  open = 'open',
  refrigerator = 'refrigerator',
  dumpTruck = 'dumpTruck',
  tent = 'tent',
  trawl = 'trawl',
  allMetal = 'allMetal',
  curtain = 'curtain',
}
